# Generated by Django 5.1.4 on 2025-03-08 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PetSitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Appr', 'Approved'), ('InPr', 'InProgress'), ('Done', 'Done'), ('Decl', 'Declined')], max_length=5)),
                ('detail', models.CharField(max_length=500)),
                ('approved_by_sitter', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('petowner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orders.petowner')),
                ('petsitter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.petsitter')),
            ],
        ),
    ]
